version: "3.7"

services:
  react_web:
    container_name: react_web
    image: react_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3002:80"
    restart: always
